### PR TITLE
Add arm builds for 0.12.10

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

❗Do *not* merge into `main`. 

This creates arm builds for the 0.12.10 version. 

Unfortunately, manim [requires](https://github.com/ManimCommunity/manim/blob/aeeb6da3572e89fac605872288988823c93ea146/pyproject.toml#L49) an arm build of `mapbox_earcut` version 0.12.x.

@ChrisBarker-NOAA could you please create a new branch called `01210` in the `conda-forge/mapbox_earcut-feedstock` repository with the state of [`pavelzw/mapbox_earcut-feedstock@01210`](https://github.com/pavelzw/mapbox_earcut-feedstock/tree/01210)? Like this, we can still update the builds of older releases without modifying the new ones.

### CODE REVIEW

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Changed base to the newly created branch `0.12.10` and retriggered CI.

**Comment by pavelzw** [comment]
Thanks @xhochy!

**Comment by xhochy** [comment]
@pavelzw Try adding `pip<22` to the host

**Comment by xhochy** [comment]
You will need `make` in `build`, too.

**Comment by pavelzw** [comment]
@ChrisBarker-NOAA ready for review/merge. Thanks for your help @xhochy!

**Comment by ChrisBarker-NOAA** [comment]
Hmm - why did pip ned to get pinned?

Has anyone pinged the upstream project? -- this seems a bit unsustainable in the long run.

I don't see a Issue or PR there: https://github.com/skogler/mapbox_earcut_python

**Pull request merged**
