### PR TITLE
Add cross-compilation for arm

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Add cross compilation for linux-aarch64 and osx-arm64.

### CODE REVIEW

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Comment by ChrisBarker-NOAA** [comment]
looks like it's all building -- thanks!

**Comment by pavelzw** [comment]
@ChrisBarker-NOAA could you please merge this PR? I need it for the arm build of the [manim](https://anaconda.org/conda-forge/manim) package.

**Comment by ChrisBarker-NOAA** [comment]
Sorry about that -- I thought I *had* merged it! Must have missed the last confirmation button.

**Comment by pavelzw** [comment]
Thanks!

**Pull request merged**
